name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ '17' ]  # Specify the Java version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenJDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'  # 'temurin' is the recommended OpenJDK distribution

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests with test profile
        run: mvn test -Dspring.profiles.active=test
      - name: Install dependencies and test
        run: mvn clean install

      - name: Package application
        run: mvn package -DskipTests=true

      - name: Archive the artifact
        uses: actions/upload-artifact@v3
        with:
          name: springboot-app
          path: target/*.jar